export const boots = [
  {
    //id: "f101bd3d-ef98-415c-ac8d-dea5e4d058ef",
    name: "Sandals",
    item: "accessory",
    type: "speed",
    icon: "/assets/sandal.png",
    value: 1,
    equippable: true,
    usable: false,
    buy: 10,
    sell: 2,
  },
  {
    //id: "b7223cb9-348f-42b1-8d24-942d29d69e19",
    name: "Leather Boots",
    item: "accessory",
    type: "speed",
    icon: "/assets/leather-boot.png",
    value: 2,
    equippable: true,
    usable: false,
    buy: 20,
    sell: 4,
  },
  {
    //id: "6f42419b-d1aa-44da-b026-a372971930ca",
    name: "Spiked Boots",
    item: "accessory",
    type: "speed",
    icon: "/assets/steeltoe-boots.png",
    value: 3,
    equippable: true,
    usable: false,
    buy: 30,
    sell: 6,
  },
  {
    //id: "8c92ef96-2e4c-4d60-8af4-56af0958882c",
    name: "Fancy Boots",
    item: "accessory",
    type: "speed",
    icon: "/assets/walking-boot.png",
    value: 4,
    equippable: true,
    usable: false,
    buy: 40,
    sell: 8,
  },
  {
    //id: "7e6ec5e4-a5bf-4d9d-9a34-0ac4ab5b2913",
    name: "Winged Boots",
    item: "accessory",
    type: "speed",
    icon: "/assets/wingfoot.png",
    value: 5,
    equippable: true,
    usable: false,
    buy: 50,
    sell: 10,
  },
];

export const gloves = [
  {
    //id: "e4cfb214-0988-45f3-a4ae-f690fcd346f6",
    name: "Fingerless Gloves",
    item: "accessory",
    type: "physical attack",
    icon: "/assets/gloves.png",
    value: 5,
    equippable: true,
    usable: false,
    buy: 15,
    sell: 3,
  },
  {
    //id: "bfc34b6e-a2a6-4252-b112-c6ae9f97193f",
    name: "Leather Gloves",
    item: "accessory",
    type: "physical attack",
    icon: "/assets/gloves.png",
    value: 10,
    equippable: true,
    usable: false,
    buy: 30,
    sell: 6,
  },
  {
    //id: "5bd66341-e039-4cb1-bd5e-ba1e46237774",
    name: "Studded Leather Gloves",
    item: "accessory",
    type: "physical attack",
    icon: "/assets/gloves.png",
    value: 15,
    equippable: true,
    usable: false,
    buy: 45,
    sell: 9,
  },
  {
    //id: "c4fcd1ec-29e2-4aed-a5ff-78d5f4a0cf62",
    name: "Mail Gloves",
    item: "accessory",
    type: "physical attack",
    icon: "/assets/gloves.png",
    value: 20,
    equippable: true,
    usable: false,
    buy: 60,
    sell: 12,
  },
  {
    //id: "99fa1366-aa69-4112-8764-84fa080887c1",
    name: "Plate Gauntlets",
    item: "accessory",
    type: "physical attack",
    icon: "/assets/gauntlet.png",
    value: 25,
    equippable: true,
    usable: false,
    buy: 75,
    sell: 15,
  },
];

export const bracelets = [
  {
    //id: "03523c42-64f6-4044-b2df-84eae29ea51c",
    name: "Copper Bracelet",
    item: "accessory",
    type: "physical defense",
    icon: "/assets/ring.png",
    value: 5,
    equippable: true,
    usable: false,
    buy: 15,
    sell: 3,
  },
  {
    //id: "9b21716c-b5e1-45d5-8064-f3eba6eae09c",
    name: "Bronze Bracelet",
    item: "accessory",
    type: "physical defense",
    icon: "/assets/ring.png",
    value: 10,
    equippable: true,
    usable: false,
    buy: 30,
    sell: 6,
  },
  {
    //id: "a305b5fa-82dc-4a46-beb2-0dfd614c9e61",
    name: "Steel Bracelet",
    item: "accessory",
    type: "physical defense",
    icon: "/assets/ring.png",
    value: 15,
    equippable: true,
    usable: false,
    buy: 45,
    sell: 9,
  },
  {
    //id: "f73ff105-6a85-4740-805f-94028f1ba33e",
    name: "Platinum Bracelet",
    item: "accessory",
    type: "physical defense",
    icon: "/assets/ring.png",
    value: 20,
    equippable: true,
    usable: false,
    buy: 60,
    sell: 12,
  },
  {
    //id: "69b344cb-70dc-475a-a233-af8d9a8c6d67",
    name: "Mithril Bracelet",
    item: "accessory",
    type: "physical defense",
    icon: "/assets/ring.png",
    value: 25,
    equippable: true,
    usable: false,
    buy: 75,
    sell: 15,
  },
];

export const jewelry = [
  {
    //id: "387b69f8-f0a9-4027-a122-a8cc82dd29e9",
    name: "Amber Ring",
    item: "accessory",
    type: "magical defense",
    icon: "/assets/globe-ring.png",
    value: 5,
    equippable: true,
    usable: false,
    buy: 15,
    sell: 3,
  },
  {
    //id: "6fa989fb-6c13-4263-b3af-7d9a4f1a95fb",
    name: "Sapphire Bracelet",
    item: "accessory",
    type: "magical defense",
    icon: "/assets/power-ring.png",
    value: 10,
    equippable: true,
    usable: false,
    buy: 30,
    sell: 6,
  },
  {
    //id: "797e2bed-5d94-4204-87df-8d8e47ba2b28",
    name: "Golden Torc",
    item: "accessory",
    type: "magical defense",
    icon: "/assets/torc.png",
    value: 15,
    equippable: true,
    usable: false,
    buy: 45,
    sell: 9,
  },
  {
    //id: "a205652c-6585-432b-8d0b-ca91081ab993",
    name: "Ruby Amulet",
    item: "accessory",
    type: "magical defense",
    icon: "/assets/gem-pendant.png",
    value: 20,
    equippable: true,
    usable: false,
    buy: 60,
    sell: 12,
  },
  {
    //id: "92d63a1c-1def-4ea6-ba8f-d2066421839a",
    name: "Diamond Tiara",
    item: "accessory",
    type: "magical defense",
    icon: "/assets/tiara.png",
    value: 25,
    equippable: true,
    usable: false,
    buy: 75,
    sell: 15,
  },
];

export const necklaces = [
  {
    //id: "164f44fb-0107-4e6b-bf75-1d7a368129d8",
    name: "Bone Necklace",
    item: "accessory",
    type: "magical attack",
    icon: "/assets/primitive-necklace.png",
    value: 5,
    equippable: true,
    usable: false,
    buy: 15,
    sell: 3,
  },
  {
    //id: "56238ec0-81a9-4bf1-8062-461ae41d8d04",
    name: "Tribal Necklace",
    item: "accessory",
    type: "magical attack",
    icon: "/assets/tribal-pendant.png",
    value: 10,
    equippable: true,
    usable: false,
    buy: 30,
    sell: 6,
  },
  {
    //id: "971db5c8-a098-4da7-9835-73c8e32c2213",
    name: "Feather Necklace",
    item: "accessory",
    type: "magical attack",
    icon: "/assets/feather-necklace.png",
    value: 15,
    equippable: true,
    usable: false,
    buy: 45,
    sell: 9,
  },
  {
    //id: "f296189d-3b43-48a8-8218-3645cfff6a07",
    name: "Key Pendant",
    item: "accessory",
    type: "magical attack",
    icon: "/assets/pendant-key.png",
    value: 20,
    equippable: true,
    usable: false,
    buy: 60,
    sell: 12,
  },
  {
    //id: "5fe7a606-598e-49e2-907e-9d32c18b96a7",
    name: "Emerald Necklace",
    item: "accessory",
    type: "magical attack",
    icon: "/assets/emerald-necklace.png",
    value: 25,
    equippable: true,
    usable: false,
    buy: 75,
    sell: 15,
  },
];
