export const playerStats = {
  level: 1,
  exp: 0,
  maxHealth: 25,
  name: "Brian",
  img: "/assets/barbarian.png",
  gold: 100,
  physicalDef: 0,
  magicalDef: 0,
  primary: {
    id: "790600fc-cbd6-42d3-b48e-01593f12eb16",
    name: "Dagger",
    item: "weapon",
    type: "physical",
    icon: "/assets/plain-dagger.png",
    attack: 10,
    ranged: false,
    equippable: true,
    usable: false,
    buy: 20,
    sell: 4,
  },
  secondary: {
    id: "3ef03218-0809-4abc-9524-5cd814843594",
    name: "Lesser Blast",
    item: "weapon",
    type: "magical",
    icon: "/assets/magic-swirl.png",
    attack: 10,
    ranged: true,
    equippable: true,
    usable: false,
    buy: 20,
    sell: 4,
  },
  armor: {
    id: "2ac57c80-a9fd-48b9-963e-272a91232284",
    name: "Leather Armor",
    item: "armor",
    type: "physical",
    icon: "/assets/leather-vest.png",
    defense: 25,
    equippable: true,
    usable: false,
    buy: 50,
    sell: 10,
  },
  helmet: {
    id: "3bd4e9e4-0cbb-449c-a785-d8dc26d9e7bc",
    name: "Bandana",
    item: "helmet",
    type: "magical",
    icon: "/assets/bandana.png",
    defense: 25,
    equippable: true,
    usable: false,
    buy: 50,
    sell: 10,
  },
  accessory: null,
  speed: 8,
};
export const fiends = [
  {
    level: 1,
    exp: 3,
    name: "Skeleton",
    maxHealth: 6,
    img: "/assets/skeleton.png",
    gold: 2,
    physicalDef: 9,
    magicalDef: 9,
    primary: {
      name: "Rusty Sword",
      type: "physical",
      attack: 7,
    },
    secondary: {
      name: "Bone Magic",
      type: "magical",
      attack: 16,
    },
    speed: 2,
  },
  {
    level: 1,
    exp: 2,
    name: "Rat",
    maxHealth: 4,
    img: "/assets/rat.png",
    gold: 2,
    physicalDef: 8,
    magicalDef: 9,
    primary: {
      name: "Teeth",
      type: "physical",
      attack: 3,
    },
    secondary: {
      name: "Rabies",
      type: "magical",
      attack: 11,
    },
    speed: 3,
  },
  {
    level: 1,
    exp: 6,
    name: "Bat",
    maxHealth: 8,
    img: "/assets/bat.png",
    gold: 1,
    physicalDef: 2,
    magicalDef: 5,
    primary: {
      name: "Claws",
      type: "physical",
      attack: 8,
    },
    secondary: {
      name: "Sonic Screech",
      type: "magical",
      attack: 4,
    },
    speed: 2,
    flying: true,
  },
  {
    level: 1,
    exp: 1,
    name: "Slime",
    maxHealth: 6,
    img: "/assets/slime.png",
    gold: 4,
    physicalDef: 4,
    magicalDef: 12,
    primary: {
      name: "Ooze",
      type: "physical",
      attack: 11,
    },
    secondary: {
      name: "Envelop",
      type: "magical",
      attack: 6,
    },
    speed: 3,
  },
  {
    level: 2,
    exp: 8,
    name: "Goblin",
    maxHealth: 16,
    img: "/assets/goblin.png",
    gold: 7,
    physicalDef: 12,
    magicalDef: 2,
    primary: {
      name: "Dagger",
      type: "physical",
      attack: 20,
    },
    secondary: {
      name: "Hedge Magic",
      type: "magical",
      attack: 22,
    },
    speed: 10,
  },
  {
    level: 2,
    exp: 7,
    name: "Evil Gnome",
    maxHealth: 10,
    img: "/assets/bad-gnome.png",
    gold: 10,
    physicalDef: 12,
    magicalDef: 9,
    primary: {
      name: "Dirk",
      type: "physical",
      attack: 12,
    },
    secondary: {
      name: "Creeping Mold",
      type: "magical",
      attack: 16,
    },
    speed: 4,
  },
  {
    level: 2,
    name: "Ghost",
    img: "/assets/ghost.png",
    maxHealth: 9,
    primary: {
      name: "Drain",
      type: "physical",
      attack: 10,
    },
    secondary: {
      name: "Cold Touch",
      type: "magical",
      attack: 14,
    },
    physicalDef: 1,
    magicalDef: 11,
    speed: 1,
    exp: 4,
    gold: 6,
  },
  {
    level: 4,
    name: "Giant Frog",
    img: "/assets/frog.png",
    maxHealth: 13,
    primary: {
      name: "Flying Leap",
      type: "physical",
      attack: 24,
    },
    secondary: {
      name: "Slurp",
      type: "physical",
      attack: 18,
    },
    physicalDef: 15,
    magicalDef: 14,
    speed: 4,
    exp: 17,
    gold: 12,
  },
  {
    level: 4,
    name: "Zombie",
    img: "/assets/shambling-zombie.png",
    maxHealth: 21,
    primary: {
      name: "Bite",
      type: "physical",
      attack: 24,
    },
    secondary: {
      name: "Putrid Breath",
      type: "magical",
      attack: 24,
    },
    physicalDef: 7,
    magicalDef: 17,
    speed: 3,
    exp: 14,
    gold: 13,
  },
  {
    level: 5,
    name: "Imp",
    img: "/assets/imp.png",
    maxHealth: 21,
    primary: {
      name: "Barbed Tail",
      type: "physical",
      attack: 18,
    },
    secondary: {
      name: "Fire",
      type: "magical",
      attack: 8,
    },
    physicalDef: 8,
    magicalDef: 17,
    speed: 4,
    exp: 17,
    gold: 15,
    flying: true,
  },
  {
    level: 6,
    name: "Spider",
    img: "/assets/spider-alt.png",
    maxHealth: 31,
    primary: {
      name: "Bite",
      type: "physical",
      attack: 22,
    },
    secondary: {
      name: "Web",
      type: "magical",
      attack: 15,
    },
    physicalDef: 19,
    magicalDef: 16,
    speed: 4,
    exp: 16,
    gold: 25,
  },
  {
    level: 6,
    name: "Giant Crab",
    img: "/assets/crab.png",
    maxHealth: 27,
    primary: {
      name: "Claws",
      type: "physical",
      attack: 25,
    },
    secondary: {
      name: "Drown",
      type: "magical",
      attack: 15,
    },
    physicalDef: 21,
    magicalDef: 15,
    speed: 7,
    exp: 23,
    gold: 28,
  },
  {
    level: 7,
    name: "Killer Wasp",
    img: "/assets/wasp-sting.png",
    maxHealth: 39,
    primary: {
      name: "Battering Wings",
      type: "magical",
      attack: 13,
    },
    secondary: {
      name: "Sting",
      type: "physical",
      attack: 26,
    },
    physicalDef: 25,
    magicalDef: 27,
    speed: 3,
    exp: 27,
    gold: 22,
    flying: true,
  },
  {
    level: 7,
    name: "Mantis",
    img: "/assets/praying-mantis.png",
    maxHealth: 33,
    primary: {
      name: "Razor Claws",
      type: "physical",
      attack: 25,
    },
    secondary: {
      name: "Devour",
      type: "physical",
      attack: 27,
    },
    physicalDef: 15,
    magicalDef: 28,
    speed: 8,
    exp: 28,
    gold: 27,
  },
  {
    level: 8,
    name: "Mummy",
    img: "/assets/mummy-head.png",
    maxHealth: 35,
    primary: {
      name: "Necrotic Grasp",
      type: "magical",
      attack: 23,
    },
    secondary: {
      name: "Dessicate",
      type: "magical",
      attack: 24,
    },
    physicalDef: 30,
    magicalDef: 33,
    speed: 5,
    exp: 23,
    gold: 28,
  },
  {
    level: 8,
    name: "Giant Snake",
    img: "/assets/snake.png",
    maxHealth: 37,
    primary: {
      name: "Bite",
      type: "physical",
      attack: 12,
    },
    secondary: {
      name: "Constrict",
      type: "physical",
      attack: 26,
    },
    physicalDef: 26,
    magicalDef: 25,
    speed: 2,
    exp: 23,
    gold: 23,
  },
  {
    level: 8,
    name: "Troglodyte",
    img: "/assets/troglodyte.png",
    maxHealth: 47,
    primary: {
      name: "Talons",
      type: "physical",
      attack: 15,
    },
    secondary: {
      name: "Awful Stench",
      type: "physical",
      attack: 17,
    },
    physicalDef: 33,
    magicalDef: 33,
    speed: 6,
    exp: 30,
    gold: 27,
  },
  {
    level: 9,
    name: "Giant Centipede",
    img: "/assets/centipede.png",
    maxHealth: 45,
    primary: {
      name: "Bite",
      type: "physical",
      attack: 29,
    },
    secondary: {
      name: "Engulf",
      type: "physical",
      attack: 24,
    },
    physicalDef: 39,
    magicalDef: 0,
    speed: 7,
    exp: 30,
    gold: 28,
  },
  {
    level: 9,
    name: "Fish-Man",
    img: "/assets/fish-monster.png",
    maxHealth: 32,
    primary: {
      name: "Trident",
      type: "physical",
      attack: 21,
    },
    secondary: {
      name: "Water Magic",
      type: "magical",
      attack: 21,
    },
    physicalDef: 33,
    magicalDef: 27,
    speed: 8,
    exp: 34,
    gold: 36,
  },
  {
    level: 10,
    name: "Medusa",
    img: "/assets/medusa-head.png",
    maxHealth: 42,
    primary: {
      name: "Snakebites",
      type: "physical",
      attack: 29,
    },
    secondary: {
      name: "Gaze",
      type: "magical",
      attack: 28,
    },
    physicalDef: 26,
    magicalDef: 31,
    speed: 5,
    exp: 36,
    gold: 30,
  },
  {
    level: 10,
    name: "Salamander",
    img: "/assets/salamander.png",
    maxHealth: 29,
    primary: {
      name: "Burn",
      type: "physical",
      attack: 28,
    },
    secondary: {
      name: "Immolate",
      type: "magical",
      attack: 21,
    },
    physicalDef: 43,
    magicalDef: 27,
    speed: 7,
    exp: 42,
    gold: 36,
  },
  {
    level: 11,
    name: "Bear",
    img: "/assets/bear-head.png",
    maxHealth: 62,
    primary: {
      name: "Jaws",
      type: "physical",
      attack: 42,
    },
    secondary: {
      name: "Paws",
      type: "physical",
      attack: 25,
    },
    physicalDef: 46,
    magicalDef: 26,
    speed: 10,
    exp: 44,
    gold: 41,
  },
  {
    level: 12,
    name: "Evil Book",
    img: "/assets/evil-book.png",
    maxHealth: 53,
    primary: {
      name: "Greater Blast",
      type: "magical",
      attack: 52,
    },
    secondary: {
      name: "Negative Reviews",
      type: "magical",
      attack: 32,
    },
    physicalDef: 0,
    magicalDef: 49,
    speed: 7,
    exp: 38,
    gold: 44,
    flying: true,
  },
  {
    level: 12,
    name: "Carnivorous Plant",
    img: "/assets/carnivorous-plant.png",
    maxHealth: 55,
    primary: {
      name: "Devour",
      type: "physical",
      attack: 40,
    },
    secondary: {
      name: "Thorny Lash",
      type: "physical",
      attack: 33,
    },
    physicalDef: 53,
    magicalDef: 42,
    speed: 4,
    exp: 34,
    gold: 47,
  },
  {
    level: 13,
    name: "Megascorpion",
    img: "/assets/scorpion.png",
    maxHealth: 67,
    primary: {
      name: "Pincers",
      type: "physical",
      attack: 37,
    },
    secondary: {
      name: "Stinging Tail",
      type: "physical",
      attack: 38,
    },
    physicalDef: 36,
    magicalDef: 48,
    speed: 5,
    exp: 56,
    gold: 56,
  },
  {
    level: 14,
    name: "Mimic",
    img: "/assets/mimic-chest.png",
    maxHealth: 53,
    primary: {
      name: "Giant Bite",
      type: "physical",
      attack: 43,
    },
    secondary: {
      name: "Shock",
      type: "magical",
      attack: 35,
    },
    physicalDef: 30,
    magicalDef: 62,
    speed: 9,
    exp: 52,
    gold: 47,
  },
  {
    level: 14,
    name: "Spectre",
    img: "/assets/spectre.png",
    maxHealth: 58,
    primary: {
      name: "Siphon",
      type: "physical",
      attack: 43,
    },
    secondary: {
      name: "Spectral Grasp",
      type: "magical",
      attack: 33,
    },
    physicalDef: 1,
    magicalDef: 63,
    speed: 8,
    exp: 51,
    gold: 49,
  },
  {
    level: 15,
    name: "Tunnel Worm",
    img: "/assets/leeching-worm.png",
    maxHealth: 81,
    primary: {
      name: "Rasp",
      type: "physical",
      attack: 33,
    },
    secondary: {
      name: "Swallow",
      type: "physical",
      attack: 31,
    },
    physicalDef: 60,
    magicalDef: 62,
    speed: 6,
    exp: 47,
    gold: 56,
  },
  {
    level: 15,
    name: "Fire Elemental",
    img: "/assets/unfriendly-fire.png",
    maxHealth: 80,
    primary: {
      name: "Flashfire",
      type: "physical",
      attack: 29,
    },
    secondary: {
      name: "Incinerate",
      type: "magical",
      attack: 33,
    },
    physicalDef: 39,
    magicalDef: 63,
    speed: 10,
    exp: 52,
    gold: 50,
  },
  {
    level: 16,
    name: "Gargoyle",
    img: "/assets/gargoyle.png",
    maxHealth: 81,
    primary: {
      name: "Stone Grasp",
      type: "physical",
      attack: 47,
    },
    secondary: {
      name: "Grinding Bite",
      type: "physical",
      attack: 25,
    },
    physicalDef: 50,
    magicalDef: 50,
    speed: 10,
    exp: 68,
    gold: 58,
  },
  {
    level: 16,
    name: "Giant Croc",
    img: "/assets/croc-jaws.png",
    maxHealth: 69,
    primary: {
      name: "Enormous Bite",
      type: "physical",
      attack: 41,
    },
    secondary: {
      name: "Death Roll",
      type: "physical",
      attack: 52,
    },
    physicalDef: 56,
    magicalDef: 53,
    speed: 11,
    exp: 53,
    gold: 51,
  },
  {
    level: 18,
    name: "Werewolf",
    img: "/assets/werewolf.png",
    maxHealth: 94,
    primary: {
      name: "Rip & Tear",
      type: "physical",
      attack: 50,
    },
    secondary: {
      name: "Lycanthropic Bite",
      type: "magical",
      attack: 35,
    },
    physicalDef: 51,
    magicalDef: 47,
    speed: 8,
    exp: 64,
    gold: 62,
  },
  {
    level: 18,
    name: "Vampire",
    img: "/assets/female-vampire.png",
    maxHealth: 112,
    primary: {
      name: "Suck Your Blood",
      type: "physical",
      attack: 51,
    },
    secondary: {
      name: "Stupefy",
      type: "magical",
      attack: 41,
    },
    physicalDef: 60,
    magicalDef: 30,
    speed: 9,
    exp: 52,
    gold: 64,
  },
  {
    level: 19,
    name: "Minotaur",
    img: "/assets/minotaur.png",
    maxHealth: 100,
    primary: {
      name: "Gore",
      type: "physical",
      attack: 33,
    },
    secondary: {
      name: "Bull Rush",
      type: "magical",
      attack: 44,
    },
    physicalDef: 56,
    magicalDef: 81,
    speed: 9,
    exp: 74,
    gold: 63,
  },
  {
    level: 19,
    name: "Creepy",
    img: "/assets/gluttonous-smile.png",
    maxHealth: 98,
    primary: {
      name: "Gobble",
      type: "physical",
      attack: 51,
    },
    secondary: {
      name: "Ravage",
      type: "magical",
      attack: 40,
    },
    physicalDef: 81,
    magicalDef: 86,
    speed: 13,
    exp: 57,
    gold: 79,
  },
  {
    level: 20,
    name: "Orc",
    img: "/assets/orc-head.png",
    maxHealth: 97,
    primary: {
      name: "Hack",
      type: "physical",
      attack: 47,
    },
    secondary: {
      name: "Slash",
      type: "physical",
      attack: 50,
    },
    physicalDef: 81,
    magicalDef: 30,
    speed: 8,
    exp: 70,
    gold: 70,
  },
  {
    level: 20,
    name: "Wyvern",
    img: "/assets/wyvern.png",
    maxHealth: 105,
    primary: {
      name: "Hack",
      type: "physical",
      attack: 49,
    },
    secondary: {
      name: "Slash",
      type: "physical",
      attack: 54,
    },
    physicalDef: 37,
    magicalDef: 68,
    speed: 9,
    exp: 70,
    gold: 63,
  },
  {
    level: 21,
    name: "Wyvern",
    img: "/assets/wyvern.png",
    maxHealth: 107,
    primary: {
      name: "Talons",
      type: "physical",
      attack: 53,
    },
    secondary: {
      name: "Shriek",
      type: "magical",
      attack: 65,
    },
    physicalDef: 60,
    magicalDef: 69,
    speed: 15,
    exp: 94,
    gold: 70,
  },
  {
    level: 21,
    name: "Ifrit",
    img: "/assets/ifrit.png",
    maxHealth: 109,
    primary: {
      name: "Giant Claws",
      type: "physical",
      attack: 50,
    },
    secondary: {
      name: "Fire Cyclone",
      type: "magical",
      attack: 52,
    },
    physicalDef: 87,
    magicalDef: 70,
    speed: 13,
    exp: 69,
    gold: 69,
  },
  {
    level: 21,
    name: "Djinn",
    img: "/assets/djinn.png",
    maxHealth: 124,
    primary: {
      name: "Scimitar",
      type: "physical",
      attack: 69,
    },
    secondary: {
      name: "Whirlwind",
      type: "magical",
      attack: 37,
    },
    physicalDef: 65,
    magicalDef: 70,
    speed: 6,
    exp: 71,
    gold: 68,
  },
  {
    level: 22,
    name: "Lesser Dragon",
    img: "/assets/dragon-head.png",
    maxHealth: 112,
    primary: {
      name: "Raking Claws",
      type: "physical",
      attack: 64,
    },
    secondary: {
      name: "Fire Breath",
      type: "magical",
      attack: 40,
    },
    physicalDef: 80,
    magicalDef: 74,
    speed: 13,
    exp: 73,
    gold: 68,
  },
  {
    level: 22,
    name: "Ogre",
    img: "/assets/ogre.png",
    maxHealth: 112,
    primary: {
      name: "Club",
      type: "physical",
      attack: 65,
    },
    secondary: {
      name: "Smash",
      type: "physical",
      attack: 56,
    },
    physicalDef: 57,
    magicalDef: 64,
    speed: 12,
    exp: 74,
    gold: 94,
  },
  {
    level: 23,
    name: "Stone Golem",
    img: "/assets/rock-golem.png",
    maxHealth: 102,
    primary: {
      name: "Pummel",
      type: "physical",
      attack: 54,
    },
    secondary: {
      name: "Stone Fists",
      type: "physical",
      attack: 73,
    },
    physicalDef: 89,
    magicalDef: 68,
    speed: 12,
    exp: 76,
    gold: 79,
  },
  {
    level: 23,
    name: "Troll",
    img: "/assets/troll.png",
    maxHealth: 114,
    primary: {
      name: "Filthy Nails",
      type: "physical",
      attack: 59,
    },
    secondary: {
      name: "Gnaw",
      type: "physical",
      attack: 65,
    },
    physicalDef: 71,
    magicalDef: 81,
    speed: 11,
    exp: 80,
    gold: 89,
  },
  {
    level: 24,
    name: "Giant",
    img: "/assets/giant.png",
    maxHealth: 121,
    primary: {
      name: "Stomp",
      type: "physical",
      attack: 56,
    },
    secondary: {
      name: "Rend",
      type: "physical",
      attack: 54,
    },
    physicalDef: 93,
    magicalDef: 79,
    speed: 12,
    exp: 75,
    gold: 70,
  },
  {
    level: 24,
    name: "Ice Golem",
    img: "/assets/ice-golem.png",
    maxHealth: 109,
    primary: {
      name: "Freeze",
      type: "magical",
      attack: 50,
    },
    secondary: {
      name: "Ice Spear",
      type: "physical",
      attack: 65,
    },
    physicalDef: 91,
    magicalDef: 89,
    speed: 9,
    exp: 105,
    gold: 85,
  },
  {
    level: 25,
    name: "Hydra",
    img: "/assets/hydra.png",
    maxHealth: 124,
    primary: {
      name: "Multi-Bite",
      type: "physical",
      attack: 76,
    },
    secondary: {
      name: "Tail Lash",
      type: "physical",
      attack: 43,
    },
    physicalDef: 73,
    magicalDef: 90,
    speed: 15,
    exp: 87,
    gold: 75,
  },
  {
    level: 25,
    name: "Greater Dragon",
    img: "/assets/spiked-dragon-head.png",
    maxHealth: 120,
    primary: {
      name: "Spike Teeth",
      type: "physical",
      attack: 52,
    },
    secondary: {
      name: "Poison Breath",
      type: "magical",
      attack: 75,
    },
    physicalDef: 78,
    magicalDef: 103,
    speed: 11,
    exp: 87,
    gold: 76,
  },
];
