export const playerStats = {
  level: 1,
  exp: 10,
  maxHealth: 25,
  name: "Brian",
  img: "/assets/barbarian.png",
  gold: 10,
  physicalDef: 0,
  magicalDef: 0,
  primary: {
    name: "Rapier",
    item: "weapon",
    type: "physical",
    icon: "/assets/stiletto.png",
    attack: 25,
    ranged: false,
  },
  secondary: {
    name: "Lesser Blast",
    item: "weapon",
    type: "magical",
    icon: "/assets/magic-swirl.png",
    attack: 25,
    ranged: true,
  },
  armor: {
    name: "Leather Armor",
    item: "armor",
    type: "physical",
    icon: "/assets/leather-vest.png",
    defense: 25,
  },
  helmet: {
    name: "Feather Cap",
    item: "helmet",
    type: "magical",
    icon: "/assets/feather-cap.png",
    defense: 25,
  },
  speed: 8,
};
export const fiends = [
  {
    level: 1,
    exp: 5,
    name: "Skeleton",
    maxHealth: 10,
    img: "/assets/skeleton.png",
    gold: 5,
    physicalDef: 10,
    magicalDef: 10,
    primary: {
      name: "Rusty Sword",
      type: "physical",
      attack: 5,
    },
    secondary: {
      name: "Bone Magic",
      type: "magical",
      attack: 5,
    },
    speed: 4,
  },
  {
    level: 1,
    exp: 3,
    name: "Rat",
    maxHealth: 5,
    img: "/assets/rat.png",
    gold: 2,
    physicalDef: 5,
    magicalDef: 5,
    primary: {
      name: "Teeth",
      type: "physical",
      attack: 3,
    },
    secondary: {
      name: "Rabies",
      type: "magical",
      attack: 3,
    },
    speed: 8,
  },
  {
    level: 1,
    exp: 3,
    name: "Bat",
    maxHealth: 7,
    img: "/assets/bat.png",
    gold: 3,
    physicalDef: 4,
    magicalDef: 4,
    primary: {
      name: "Claws",
      type: "physical",
      attack: 2,
    },
    secondary: {
      name: "Sonic Screech",
      type: "magical",
      attack: 5,
    },
    speed: 6,
  },
  {
    level: 1,
    exp: 6,
    name: "Slime",
    maxHealth: 8,
    img: "/assets/slime.png",
    gold: 1,
    physicalDef: 1,
    magicalDef: 1,
    primary: {
      name: "Ooze",
      type: "physical",
      attack: 1,
    },
    secondary: {
      name: "Envelop",
      type: "magical",
      attack: 2,
    },
    speed: 1,
  },
  {
    level: 1,
    exp: 10,
    name: "Goblin",
    maxHealth: 15,
    img: "/assets/goblin.png",
    gold: 10,
    physicalDef: 20,
    magicalDef: 16,
    primary: {
      name: "Dagger",
      type: "physical",
      attack: 10,
    },
    secondary: {
      name: "Hedge Magic",
      type: "magical",
      attack: 8,
    },
    speed: 10,
  },
];
