export const magic = [
  {
    //id: "3ef03218-0809-4abc-9524-5cd814843594",
    name: "Lesser Blast",
    item: "weapon",
    type: "magical",
    icon: require("../images/magic-swirl.png"),
    attack: 10,
    ranged: true,
    equippable: true,
    usable: false,
    buy: 20,
    sell: 4,
  },
  {
    //id: "3ef03218-0809-4abc-9524-5cd814843594",
    name: "Blast",
    item: "weapon",
    type: "magical",
    icon: require("../images/magic-swirl.png"),
    attack: 25,
    ranged: true,
    equippable: true,
    usable: false,
    buy: 50,
    sell: 10,
  },
  {
    //id: "3ef03218-0809-4abc-9524-5cd814843594",
    name: "Greater Blast",
    item: "weapon",
    type: "magical",
    icon: require("../images/magic-swirl.png"),
    attack: 40,
    ranged: true,
    equippable: true,
    usable: false,
    buy: 80,
    sell: 16,
  },
  {
    //id: "3ef03218-0809-4abc-9524-5cd814843594",
    name: "Minor Fireball",
    item: "weapon",
    type: "magical",
    icon: require("../images/magic-swirl.png"),
    attack: 55,
    ranged: true,
    equippable: true,
    usable: false,
    buy: 110,
    sell: 22,
  },
  {
    //id: "3ef03218-0809-4abc-9524-5cd814843594",
    name: "Fireball",
    item: "weapon",
    type: "magical",
    icon: require("../images/magic-swirl.png"),
    attack: 70,
    ranged: true,
    equippable: true,
    usable: false,
    buy: 140,
    sell: 28,
  },
  {
    //id: "3ef03218-0809-4abc-9524-5cd814843594",
    name: "Major Fireball",
    item: "weapon",
    type: "magical",
    icon: require("../images/magic-swirl.png"),
    attack: 85,
    ranged: true,
    equippable: true,
    usable: false,
    buy: 170,
    sell: 34,
  },
  {
    //id: "3ef03218-0809-4abc-9524-5cd814843594",
    name: "Magic Spear",
    item: "weapon",
    type: "magical",
    icon: require("../images/magic-swirl.png"),
    attack: 100,
    ranged: true,
    equippable: true,
    usable: false,
    buy: 200,
    sell: 40,
  },
];

export const scrolls = [
  {
    //id: "1",
    name: "Scroll of Healing I",
    item: "scroll",
    effect: "heal",
    value: 20,
    description:
      "Use this scroll to gain 20 HP. Scrolls can only be used once.",
    icon: require("../images/scroll-unfurled.png"),
    equippable: false,
    usable: true,
    buy: 40,
    sell: 8,
  },
  {
    //id: "1",
    name: "Scroll of Healing II",
    item: "scroll",
    effect: "heal",
    value: 50,
    description:
      "Use this scroll to gain 50 HP. Scrolls can only be used once.",
    icon: require("../images/scroll-unfurled.png"),
    equippable: false,
    usable: true,
    buy: 100,
    sell: 20,
  },
  {
    //id: "1",
    name: "Scroll of Healing III",
    item: "scroll",
    effect: "heal",
    value: 100,
    description:
      "Use this scroll to gain 100 HP. Scrolls can only be used once.",
    icon: require("../images/scroll-unfurled.png"),
    equippable: false,
    usable: true,
    buy: 200,
    sell: 40,
  },
  {
    //id: "1576e7b7-42ef-4b7c-a807-b012832dd60e",
    name: "Scroll of Return",
    item: "scroll",
    effect: "exit",
    description:
      "Use this scroll to exit the dungeon. Scrolls can only be used once.",
    icon: require("../images/scroll-unfurled.png"),
    equippable: false,
    usable: true,
    buy: 75,
    sell: 15,
  },
];
