export const questItems = [
  {
    id: "f457d6e4-9d07-4caf-84d0-d0421ecf1072",
    item: "misc",
    name: "Skull",
    description: "An old empty skull",
    icon: require("../images/death-skull.png"),
  },
  {
    id: "2367e851-7e10-47ab-baa3-88a90ad86399",
    item: "misc",
    name: "Rat Tail",
    description: "A pink, hairless rodent tail",
    icon: require("../images/rat.png"),
  },
  {
    id: "307d0420-601e-43bc-bc3f-127e6997e3e0",
    item: "misc",
    name: "Bat Wing",
    description: "A black, leathery wing",
    icon: require("../images/bat-wing.png"),
  },
  {
    id: "eda8f50c-b0fa-4477-b848-5f79e7fc03e8",
    item: "misc",
    name: "Glob of Slime",
    description: "A disgusting blob of goo",
    icon: require("../images/transparent-slime.png"),
  },
  {
    id: "a337b52b-506b-48cf-acbe-f2cc635471cd",
    item: "misc",
    name: "Goblin Tooth",
    description: "a sharp, yellowed tooth",
    icon: require("../images/fangs.png"),
  },
  {
    id: "f9c95e63-bf51-4c94-8e10-63b65f023df1",
    item: "misc",
    name: "Gnome Hat",
    description: "A jaunty, pointed hat",
    icon: require("../images/party-hat.png"),
  },
  {
    id: "5f3b9b24-5e1c-4856-82c6-4b844b25b382",
    item: "misc",
    name: "Ectoplasm",
    description: "A vial of a ghostly, glowing substance",
    icon: require("../images/transparent-slime.png"),
  },
  {
    id: "d12ce4ce-32a0-4ce3-82ee-7559b0367611",
    item: "misc",
    name: "Frog Tongue",
    description:
      "A long, sticky frog tongue; still has a fly or two stuck to it",
    icon: require("../images/frog.png"),
  },
  {
    id: "8d6ecab5-fee0-4831-b9db-75c4883d0380",
    item: "misc",
    name: "Rotten Flesh",
    description: "A stinking chunk of rotting meat",
    icon: require("../images/carrion.png"),
  },
  {
    id: "f7f0216f-e4d4-4fd4-ab95-81a5b45bd8d3",
    item: "misc",
    name: "Imp Horn",
    description: "A demonic horn that stinks of sulfur",
    icon: require("../images/horn-internal.png"),
  },
  {
    id: "04727380-a90a-40c7-87d5-17d285480aaa",
    item: "misc",
    name: "Spider Fang",
    description: "A wickedly sharp arachnid fang",
    icon: require("../images/spider-face.png"),
  },
  {
    id: "53c6c648-b162-44a3-995c-95c799be542e",
    item: "misc",
    name: "Giant Crab Claw",
    description: "A large chitinous claw",
    icon: require("../images/crab-claw.png"),
  },
  {
    id: "f64b15b5-f0ce-418d-9668-34de837f10a1",
    item: "misc",
    name: "Killer Wasp Stinger",
    description: "A vicious vespid's venomous stinger",
    icon: require("../images/wasp-sting.png"),
  },
  {
    id: "38651078-9f60-44c6-8f9a-2a4065fb19ca",
    item: "misc",
    name: "Mantis Claw",
    description: "A barbed insect claw, only bigger",
    icon: require("../images/claw.png"),
  },
  {
    id: "3a59aa07-a434-4146-823c-4fbb761a51b6",
    item: "misc",
    name: "Old Bandage",
    description: "A stained, dessicated old bandage",
    icon: require("../images/mummy-head.png"),
  },
  {
    id: "2499c556-4932-49a8-afd6-ca5957822b37",
    item: "misc",
    name: "Snakeskin",
    description: "A scaly piece of skin from a very large snake",
    icon: require("../images/fish-scales.png"),
  },
  {
    id: "431f5efc-882b-4201-acd3-dccdf0aa177e",
    item: "misc",
    name: "Troglodyte Spike",
    description: "A misshapen spike from a troglodyte's back",
    icon: require("../images/troglodyte.png"),
  },
  {
    id: "cb1a87d4-0dd9-486a-98fa-994b5d595373",
    item: "misc",
    name: "Centipede Antenna",
    description: "A segmented antenna long enough to be a whip",
    icon: require("../images/centipede.png"),
  },
  {
    id: "9c27df43-4405-44d9-b337-7ebfcc82c920",
    item: "misc",
    name: "Fish-Man Scale",
    description: "An iridescent scale from an aquatic creature",
    icon: require("../images/fish-scales.png"),
  },
  {
    id: "c2b7d1db-1b6b-4256-90b8-5953a29b0883",
    item: "misc",
    name: "Hair-Snake",
    description: "A writhing, venomous snake from the head of a Medusa",
    icon: require("../images/medusa-head.png"),
  },
  {
    id: "f39f7858-2e39-4883-8815-504429b28a42",
    item: "misc",
    name: "Salamander Tail",
    description: "A reptilian tail, broken off as a defense mechanism",
    icon: require("../images/reptile-tail.png"),
  },
  {
    id: "c72dc5d2-2615-41aa-a112-cd1629cba5c0",
    item: "misc",
    name: "Bear Claw",
    description: "A large, sharp claw from a huge bear",
    icon: require("../images/grasping-claws.png"),
  },
  {
    id: "aba44ec5-243e-4443-87d7-dac727bebd76",
    item: "misc",
    name: "Evil Page",
    description: "A hideous page from an evil book; it might be... human skin?",
    icon: require("../images/papers.png"),
  },
  {
    id: "8c33a7c6-871b-43d5-b621-d8dffe03dd11",
    item: "misc",
    name: "Giant Leaf",
    description: "An enormous leaf from a man-eating plant",
    icon: require("../images/linden-leaf.png"),
  },
  {
    id: "f199d804-82ef-4147-bd49-319c11052796",
    item: "misc",
    name: "Megascorpion Tail",
    description: "An oversized tail and poisoned stinger",
    icon: require("../images/scorpion-tail.png"),
  },
  {
    id: "8fb04470-9786-43a5-b77f-6d4b0aafc6bc",
    item: "misc",
    name: "Mimic Tentacle",
    description: "A tentacle from a creature pretending to be a treasure chest",
    icon: require("../images/interlaced-tentacles.png"),
  },
  {
    id: "d2b0e446-3e2f-4725-b768-207a0e9b809c",
    item: "misc",
    name: "Elemental Flame",
    description: "A magical flame, all that remains of a fire elemental",
    icon: require("../images/flamer.png"),
  },
  {
    id: "10e87929-de34-4be6-b110-acce4a1afbc6",
    item: "misc",
    name: "Stone Heart",
    description: "The petrified heart of a gargoyle ",
    icon: require("../images/stone-sphere.png"),
  },
  {
    id: "29db83ca-c342-43a0-8370-07e7f860e242",
    item: "misc",
    name: "Crocodile Scale",
    description: "A large, rough scale from a giant crocodile",
    icon: require("../images/fish-scales.png"),
  },
  {
    id: "6d4eb888-6bbb-492f-b010-2a325a8b9ed7",
    item: "misc",
    name: "Lycanthropic Blood",
    description: "A small bottle of werewolf's blood",
    icon: require("../images/bleeding-wound.png"),
  },
  {
    id: "a4d2dbe5-b9dd-4a1d-8221-2605bb55c048",
    item: "misc",
    name: "Vampire Fang",
    description: "A needle-sharp fang from a bloodsucking fiend",
    icon: require("../images/fangs.png"),
  },
  {
    id: "e93fbf8d-0db3-41cb-bd7f-2a14d4d79b94",
    item: "misc",
    name: "Minotaur Hoof",
    description: "A large cloven hoof",
    icon: require("../images/hoof.png"),
  },
  {
    id: "7c4a6f94-41ba-4bbd-b537-8d05178e356b",
    item: "misc",
    name: "Orc Tusk",
    description: "A jagged tusk carved with cruce tribal designs",
    icon: require("../images/ivory-tusks.png"),
  },
  {
    id: "106a8674-b802-4699-9eee-c17fb44e89b8",
    item: "misc",
    name: "Wyvern Skin",
    description: "A tough, leathery bit of scales and skin from a wyvern",
    icon: require("../images/fish-scales.png"),
  },
  {
    id: "98c1a8d1-3723-435b-b598-0f174cdf61f3",
    item: "misc",
    name: "Ifrit Ember",
    description: "An ever-burning ember, all that remains of an ifrit",
    icon: require("../images/burning-embers.png"),
  },
  {
    id: "b5fba862-2a30-4864-bfbb-750966a53361",
    item: "misc",
    name: "Djinn Particle",
    description: "A sparkly bit of magic dust left behind by a djinn",
    icon: require("../images/sparkles.png"),
  },
  {
    id: "59c4a9d0-4d4b-47a0-9ce5-93f9ac416d71",
    item: "misc",
    name: "Dragon Meat",
    description: "A chunk of foul-smelling meat from a lesser dragon",
    icon: require("../images/meat.png"),
  },
  {
    id: "a267ebe2-2430-4010-b136-0654b59fe63f",
    item: "misc",
    name: "Ogre's Club",
    description: "A huge wooden club, crude but effective",
    icon: require("../images/wood-club.png"),
  },
  {
    id: "5dea1b2d-85e9-4274-939e-9dfc5c2580d5",
    item: "misc",
    name: "Golem Core",
    description: "The magical core of a living stone being",
    icon: require("../images/stone-sphere.png"),
  },
  {
    id: "c8644b02-b816-403f-a544-6e164336555f",
    item: "misc",
    name: "Troll Heart",
    description:
      "A rather large organ that pumps blood; troll blood, in this case",
    icon: require("../images/heart-organ.png"),
  },
  {
    id: "942cbd09-f743-4f8a-b066-87017df8b475",
    item: "misc",
    name: "Magic Bean",
    description: "A magic bean that probably grows into a giant beanstalk",
    icon: require("../images/beanstalk.png"),
  },
  {
    id: "b6dd3f46-8826-4a7c-9120-3eef9570862e",
    item: "misc",
    name: "Ice Golem Core",
    description: "The frozen core of living figure of ice",
    icon: require("../images/frozen-orb.png"),
  },
  {
    id: "212406ad-afb2-448d-b55f-5fc64b13b81a",
    item: "misc",
    name: "Hydra Tooth",
    description: "A monstrous tooth, very long and very sharp",
    icon: require("../images/needle-jaws.png"),
  },
  {
    id: "6391af1b-c53e-40f1-a3a1-34547cdcb580",
    item: "misc",
    name: "Dragon Scale",
    description: "An almost indestructible scale from a greater dragon",
    icon: require("../images/fish-scales.png"),
  },
];
