export const treasures = [
  {
    id: "7cef0bad-283b-46ce-b877-12c9d14bb537",
    name: "Short Sword",
    item: "weapon",
    type: "physical",
    icon: require("../images/piercing-sword.png"),
    attack: 30,
    ranged: false,
    equippable: true,
    usable: false,
    buy: 60,
    sell: 12,
  },
  {
    id: "9ed409e6-36af-4773-8310-f1b275917a4b",
    name: "Long Sword",
    item: "weapon",
    type: "physical",
    icon: require("../images/croc-sword.png"),
    attack: 40,
    ranged: false,
    equippable: true,
    usable: false,
    buy: 80,
    sell: 16,
  },
  {
    id: "b7223cb9-348f-42b1-8d24-942d29d69e19",
    name: "Leather Boots",
    item: "accessory",
    type: "speed",
    icon: require("../images/leather-boot.png"),
    value: 2,
    equippable: true,
    usable: false,
    buy: 20,
    sell: 4,
  },
  {
    id: "bfc34b6e-a2a6-4252-b112-c6ae9f97193f",
    name: "Leather Gloves",
    item: "accessory",
    type: "physical attack",
    icon: require("../images/gloves.png"),
    value: 10,
    equippable: true,
    usable: false,
    buy: 30,
    sell: 6,
  },
  {
    id: "387b69f8-f0a9-4027-a122-a8cc82dd29e9",
    name: "Amber Ring",
    item: "accessory",
    type: "magical defense",
    icon: require("../images/globe-ring.png"),
    value: 5,
    equippable: true,
    usable: false,
    buy: 15,
    sell: 3,
  },
];
