export const treasures = [
  {
    name: "Short Sword",
    item: "weapon",
    type: "physical",
    icon: require("../images/stiletto.png"),
    attack: 35,
    ranged: false,
    equippable: true,
    usable: false,
  },
  {
    name: "Long Sword",
    item: "weapon",
    type: "physical",
    icon: require("../images/stiletto.png"),
    attack: 45,
    ranged: false,
    equippable: true,
    usable: false,
  },
  {
    name: "Leather Boots",
    item: "accessory",
    type: "speed",
    icon: require("../images/leather-boot.png"),
    value: 1,
    equippable: true,
    usable: false,
  },
  {
    name: "Leather Gloves",
    item: "accessory",
    type: "physical attack",
    icon: require("../images/gloves.png"),
    value: 10,
    equippable: true,
    usable: false,
  },
  {
    name: "Magic Ring",
    item: "accessory",
    type: "magical defense",
    icon: require("../images/ring.png"),
    value: 10,
    equippable: true,
    usable: false,
  },
];
