export const swords = [
  {
    //id: "790600fc-cbd6-42d3-b48e-01593f12eb16",
    name: "Dagger",
    item: "weapon",
    type: "physical",
    icon: "/assets/plain-dagger.png",
    attack: 10,
    ranged: false,
    equippable: true,
    usable: false,
    buy: 20,
    sell: 4,
  },
  {
    //id: "7999aa65-4a2d-4291-839d-99d715c7ff43",
    name: "Rapier",
    item: "weapon",
    type: "physical",
    icon: "/assets/stiletto.png",
    attack: 20,
    ranged: false,
    equippable: true,
    usable: false,
    buy: 40,
    sell: 8,
  },
  {
    //id: "7cef0bad-283b-46ce-b877-12c9d14bb537",
    name: "Short Sword",
    item: "weapon",
    type: "physical",
    icon: "/assets/piercing-sword.png",
    attack: 30,
    ranged: false,
    equippable: true,
    usable: false,
    buy: 60,
    sell: 12,
  },
  {
    //id: "9ed409e6-36af-4773-8310-f1b275917a4b",
    name: "Long Sword",
    item: "weapon",
    type: "physical",
    icon: "/assets/croc-sword.png",
    attack: 40,
    ranged: false,
    equippable: true,
    usable: false,
    buy: 80,
    sell: 16,
  },
  {
    //id: "5e35e275-05d0-4c60-9643-9efa4725cfa1",
    name: "Broadsword",
    item: "weapon",
    type: "physical",
    icon: "/assets/broadsword.png",
    attack: 50,
    ranged: false,
    equippable: true,
    usable: false,
    buy: 100,
    sell: 20,
  },
  {
    //id: "0d89899a-af60-4355-a854-f4cd30f4d6fc",
    name: "Bastard Sword",
    item: "weapon",
    type: "physical",
    icon: "/assets/spiral-hilt.png",
    attack: 60,
    ranged: false,
    equippable: true,
    usable: false,
    buy: 120,
    sell: 24,
  },
  {
    //id: "a31c7082-c4c1-43c8-9e89-f47ca24ee528",
    name: "Katana",
    item: "weapon",
    type: "physical",
    icon: "/assets/katana.png",
    attack: 70,
    ranged: false,
    equippable: true,
    usable: false,
    buy: 140,
    sell: 28,
  },
  {
    //id: "afb43e96-7b2e-48b5-9dbd-1c1cccd5588a",
    name: "Claymore",
    item: "weapon",
    type: "physical",
    icon: "/assets/diamond-hilt.png",
    attack: 80,
    ranged: false,
    equippable: true,
    usable: false,
    buy: 160,
    sell: 32,
  },
  {
    //id: "99e8af2b-c10c-4bf6-97b5-e6ff31db0f05",
    name: "Zweihänder",
    item: "weapon",
    type: "physical",
    icon: "/assets/two-handed-sword.png",
    attack: 90,
    ranged: false,
    equippable: true,
    usable: false,
    buy: 180,
    sell: 36,
  },
  {
    //id: "231f5c2c-7987-48f5-9f65-2a61e6bc9f89",
    name: "Mithril Sword",
    item: "weapon",
    type: "physical",
    icon: "/assets/relic-blade.png",
    attack: 100,
    ranged: false,
    equippable: true,
    usable: false,
    buy: 200,
    sell: 40,
  },
];

export const bows = [
  {
    //id: "76f8586d-6e29-499e-a22b-0410f3a5341b",
    name: "Shortbow",
    item: "weapon",
    type: "physical",
    icon: "/assets/bow-arrow.png",
    attack: 15,
    ranged: true,
    equippable: true,
    usable: false,
    buy: 30,
    sell: 6,
  },
  {
    //id: "d53c1b27-f408-4357-be54-322b9d1b7dff",
    name: "Crossbow",
    item: "weapon",
    type: "physical",
    icon: "/assets/crossbow.png",
    attack: 25,
    ranged: true,
    equippable: true,
    usable: false,
    buy: 50,
    sell: 10,
  },
  {
    //id: "0f6e4bde-a4e8-45a3-9ac2-9c947d705429",
    name: "Longbow",
    item: "weapon",
    type: "physical",
    icon: "/assets/high-shot.png",
    attack: 35,
    ranged: true,
    equippable: true,
    usable: false,
    buy: 70,
    sell: 14,
  },
  {
    //id: "8a9abef9-fdad-4d18-abdd-9cc6d98f038d",
    name: "Heavy Crossbow",
    item: "weapon",
    type: "physical",
    icon: "/assets/crossbow.png",
    attack: 45,
    ranged: true,
    equippable: true,
    usable: false,
    buy: 90,
    sell: 18,
  },
  {
    //id: "16d31fa9-4579-4677-9968-ef7b6f3b8f6d",
    name: "Recurved Bow",
    item: "weapon",
    type: "physical",
    icon: "/assets/heavy-arrow.png",
    attack: 55,
    ranged: true,
    equippable: true,
    usable: false,
    buy: 110,
    sell: 22,
  },
  {
    //id: "7ed739ed-ef54-491d-814b-6d0fe3617056",
    name: "Arbalest",
    item: "weapon",
    type: "physical",
    icon: "/assets/crossbow.png",
    attack: 65,
    ranged: true,
    equippable: true,
    usable: false,
    buy: 130,
    sell: 26,
  },
];
